server:
  port: 9090
spring:
  application:
    name: MART-SERVICE
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/martdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2

#logging:
#  level:
#    org.hibernate.SQL: DEBUG